packages = ["emfs:./mpyc_web-0.3.0-py3-none-any.whl"]

[[fetch]]
from = "./py/mpycweb"
to_folder = "./mpycweb"
files = [
    "__init__.py",
    "patches.py",
    "peerjs.py",
    "transport.py",
    "worker_init.py",
    "worker.py",
    "log.py",
    "stats.py"
]

[[fetch]]
from = "./py/"
to_folder = "./"
files = ["main.py", "mpyc_web-0.3.0-py3-none-any.whl"]
