[tool.poetry]
name = "mpyc"
version = "0.8.8"
description = "MPyC for Multiparty Computation in Python"
authors = ["Berry Schoenmakers <berry@win.tue.nl>"]
readme = "README.md"
packages = [{include = "demos"}]

[tool.poetry.dependencies]
python = "^3.10"
didcomm = "0.3.0"
peerdid = "0.4.0"
matplotlib = "^3.6.1"
qrcode = "^7.3.1"
numpy = "^1.23.4"
gmpy2 = "^2.1.2"

[tool.poetry.group.dev.dependencies]
# mpyc = {path = ".", develop = true}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
