[tool.poetry]
name = "mpyc"
version = "0.8.8"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
# python = "^3.8"
# didcomm = "0.3.0"
# peerdid = "0.4.0"
# matplotlib = "^3.6.1"
# qrcode = "^7.3.1"
# requests = "^2.28.1"
gmpy2 = "^2.1.2"
numpy = "^1.23.4"
# pandas = "^1.5.1"
# setuptools = "^65.5.0"
# pip = "^22.3"
# virtualenvwrapper = "^4.8.4"
# Authlib = "^1.1.0"
# base58 = "^2.1.1"
# varint = "^1.0.2"
# packaging = "^21.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
