# Generated by pip2nix 0.8.0.dev1
# See https://github.com/nix-community/pip2nix

{ pkgs, fetchurl, fetchgit, fetchhg }:

self: super: {

  "Authlib" = super.buildPythonPackage rec {
    pname = "Authlib";
    version = "1.1.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/d5/08/138c5ddc83862a0e6616d0ea0b6b70ac9084b0c5937c12ceb8a3acd7e123/Authlib-1.1.0-py2.py3-none-any.whl";
      sha256 = "08qmdhvz9kvvn0azvbrbaynbj1d14xdr99hhq8v264jix8fnljxy";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [ ];
    checkInputs = [ ];
    nativeBuildInputs = [ ];
    propagatedBuildInputs = [
      super."cryptography"
    ];
  };
  "attrs" = super.buildPythonPackage rec {
    pname = "attrs";
    version = "21.4.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/be/be/7abce643bfdf8ca01c48afa2ddf8308c2308b0c3b239a44e57d020afa0ef/attrs-21.4.0-py2.py3-none-any.whl";
      sha256 = "1d185347kgm169c8fs1i8rmcvv65hx4fj7w5mcv5smks9mwf69rd";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [ ];
    checkInputs = [ ];
    nativeBuildInputs = [ ];
    propagatedBuildInputs = [ ];
  };
  "didcomm" = super.buildPythonPackage rec {
    pname = "didcomm";
    version = "0.3.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/01/7b/4de46347f58aadd7aeb991798661b7eb225c5aeb74fdfe6b3eae5716b26a/didcomm-0.3.0-py3-none-any.whl";
      sha256 = "078ril21bcssrkcr3hf4fqy67jhkaav5bm7q8b41jlfd6ymw83dl";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [ ];
    checkInputs = [ ];
    nativeBuildInputs = [ ];
    propagatedBuildInputs = [
      self."Authlib"
      self."attrs"
      super."base58"
      super."packaging"
      super."pycryptodomex"
      super."varint"
    ];
  };
  "peerdid" = super.buildPythonPackage rec {
    pname = "peerdid";
    version = "0.4.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/df/2a/125bc3cdf2cce76e67c3fbe6f8a7291d40c78db8d729913b460e8ba59be4/peerdid-0.4.0-py3-none-any.whl";
      sha256 = "1qb4z9d2r3b51prkj32icwfxqi39wg6x84a2r8i7hwf8lqyafhbl";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [ ];
    checkInputs = [ ];
    nativeBuildInputs = [ ];
    propagatedBuildInputs = [
      super."base58"
      super."varint"
    ];
  };
}
