
export interface ControllerOptions {
    splitPanelSelectors: string[],
    terminalSelector: string,
    editorSelector: string,
    demoSelectSelector: string,
    hostPeerIDInputSelector: string,
    chatInputSelector: string,
    myPeerIDSelector: string,
    peersDivSelector: string,
    resetPeerIDButtonSelector: string,
    copyPeerIDButtonSelector: string,
    runMPyCButtonSelector: string,
    runMPyCAsyncButtonSelector: string,
    stopMPyCButtonSelector: string,
    connectToPeerButtonSelector: string,
    sendMessageButtonSelector: string,
    clearTerminalButtonSelector: string,
    showQRCodeButtonSelector: string,
    scanQRInputSelector: string,
    versionSelector: string,
}
