build:
	# wget https://hydra.armv7l.xyz/build/851/download/1/nixos-sd-image-22.11pre-git-armv7l-linux.img.zst
	# nix-shell -p zstd --run "unzstd nixos-sd-image-22.11pre-git-armv7l-linux.img.zst"
	# sudo dd if=nixos-sd-image-22.11pre-git-armv7l-linux.img of=/dev/mmcblk0 bs=4096 conv=fsync status=progress
